### ISSUE TITLE
terminal size is not correctly determined when using git on windows

### ISSUE THREAD

**Issue by jessesna** [Wilfred/difftastic#71]
The terminal size is not correctly determined when using git on windows with difft.
It uses the default of 80 from [here](https://github.com/Wilfred/difftastic/blob/master/src/side_by_side.rs#L241) because term_size doesn't get a valid io stream.

**Comment by Wilfred** [comment]
I think this should be fixed now, let me know if not.

**Comment by jessesna** [comment]
Thanks for the fast reponse!
The issue is still there. I checked the way how the new crate is determining it and think it won't work that way because of how git.exe starts difft.
Here's the situation:
![image](https://user-images.githubusercontent.com/78883245/145184605-60380f53-0e2e-463c-8db9-e9e2ba45e1ac.png)
I think the only way to get the correct terminal size in this situation is to query the transitive parent somehow, but that's not easy on windows i think because there's no direct API for that. `GetConsoleScreenBufferInfo` works on a handle to a io stream and there's no easy way to get such from another process. I think creating a remote thread and injecting a dll to query that would be needed, but hopefully there's an easier way.
Maybe a quick n dirty workaround for the moment would be to offer a command line parameter to specify the width?

**Comment by Wilfred** [comment]
OK, I've added a DFT_WIDTH environment variable that overrides the terminal width detection.

**Comment by jessesna** [comment]
I tinkered around a little and got a working version which is able to  determine terminal sizes of any direct or transitive parent process and i hoped you could give it a try? It can be found here: https://github.com/jessesna/difftastic/commit/f99393a0986115a6e6f576231ca429d3694690dd

Basically i wrote a wrapper for terminal-size which, only for windows, injects a dll into parent processes recursively to be able to query their console infos. The dll is part of the lib and will be "installed" on first use because, as i had to find out, there's no possibility to let cargo do the job.

Note that since it's my first experience with Rust, it might not come close to how this would be correctly handled in Rust but i'd love to make some modifications and send a PR.

**Comment by jessesna** [comment]
It's possible to [check all three streams](https://github.com/eminence/terminal-size/blob/master/examples/get_size.rs) with terminal_size but it has to be done manually.

Please note that [term_size](https://github.com/clap-rs/term_size-rs) is discontinued:

> Maintenance status
> This crate is no longer maintained. It works fine, but the maintainers don't have time and willingness to work on it or review future PRs anymore.
> 
> Consider using terminal_size instead.

**Comment by Omar-Elrefaei** [comment]
thanks Wilfred for that `DFT_WIDTH` 👍🏼 

This is my current workaround for anyone else on windows using powershell
```powershell
$Env:DFT_WIDTH=$Host.UI.RawUI.WindowSize.Width; git diff
```
so that it works perfectly when you resize the terminal window. 
If you know powershell you could manage to put this mess in a function or something, I couldn't bother to figure it out.

**Comment by Wilfred** [comment]
This has probably been fixed by #341, let me know if you still have issues.

**Comment by fredemmott** [comment]
Sorry :( this is still a problem on v0.35 which appears to include the fix from #341, both in classic cmd.exe and in Windows Terminal (either from MS Store or [GitHub](https://github.com/microsoft/terminal))


![image](https://user-images.githubusercontent.com/360927/190656310-c53533d7-ffd2-4bfb-9266-1f4a9a816e7b.png)

**Comment by jessesna** [comment]
Can confirm; neither term_size nor terminal_size are able to get the actual terminal size on Windows.
any_terminal_size has not enough reputation but would work; see https://github.com/Wilfred/difftastic/pull/77
